"""Task persistence helpers for background agent work."""

import json
import logging

logger = logging.getLogger(__name__)

def create_task_in_db(
    content: str,
    user_id: int = 0,
    priority: str = "normal",
    parent_task_id: int | None = None,
    mission_id: int | None = None,
    agent_type: str | None = None,
    metadata: dict | None = None,
    restart_state: dict | None = None,
    plan_id: int | None = None,
    plan_role: str | None = None,
    status: str = "pending",
) -> dict:
    """Insert a task into telegram_tasks for background processing.

    Args:
        content: Task description.
        user_id: Telegram user ID (0 = self-generated by bot).
        priority: 'high', 'normal', or 'low' (stored in content prefix).
        parent_task_id: If chaining, the parent task's ID.
        mission_id: Mission to link this task to. If None and parent exists,
                     inherits parent's mission_id.
        agent_type: Specialist agent to execute this task (e.g. 'programmer', 'analyst').
                    If None and parent exists, inherits parent's agent_type.
        metadata: Optional JSON-serializable task metadata persisted on telegram_tasks.
        restart_state: Optional durable restart state mirrored into dedicated DB columns and metadata.

    Returns dict with 'status' and 'task_id' or 'error'.
    """
    from db import execute as db_execute, query as db_query

    tagged_content = content

    # Determine depth (and inherit mission_id/agent_type) from parent
    depth = 0
    if parent_task_id is not None:
        try:
            parent_rows = db_query(
                "SELECT depth, mission_id, agent_type, metadata FROM telegram_tasks WHERE id = %s", (parent_task_id,)
            )
            if not parent_rows:
                return {"status": "error", "error": f"Parent task {parent_task_id} not found"}
            depth = (parent_rows[0].get("depth") or 0) + 1
            if depth >= 5:
                return {"status": "error", "error": f"Max chain depth (5) reached (current depth={depth})"}
            # Inherit mission_id from parent if not explicitly provided
            if mission_id is None:
                mission_id = parent_rows[0].get("mission_id")
            # Inherit agent_type from parent if not explicitly provided
            if agent_type is None:
                agent_type = parent_rows[0].get("agent_type")
            if metadata is None:
                metadata = parent_rows[0].get("metadata")
        except Exception as e:
            logger.error("[shared] parent depth lookup error: %s", e)
            return {"status": "error", "error": str(e)}

    try:
        metadata = dict(metadata or {})
        if restart_state is not None:
            metadata["restart_state"] = restart_state
        restart_state = metadata.get("restart_state") if isinstance(metadata.get("restart_state"), dict) else None
        metadata_json = json.dumps(metadata) if metadata else None
        rows = db_query(
            "INSERT INTO telegram_tasks (user_id, content, status, parent_task_id, depth, mission_id, agent_type, metadata, "
            "plan_id, plan_role, "
            "restart_initiated, restart_target_service, restart_completed, post_restart_phase, restart_attempt_count, restart_requested_at, resumed_after_restart, restart_reentry_block_reason) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
            (
                user_id,
                tagged_content,
                status,
                parent_task_id,
                depth,
                mission_id,
                agent_type,
                metadata_json,
                plan_id,
                plan_role,
                bool((restart_state or {}).get("restart_initiated")),
                (restart_state or {}).get("restart_target_service"),
                bool((restart_state or {}).get("restart_completed")),
                (restart_state or {}).get("post_restart_phase"),
                int((restart_state or {}).get("restart_attempt_count") or 0),
                (restart_state or {}).get("restart_requested_at"),
                bool((restart_state or {}).get("resumed_after_restart")),
                (restart_state or {}).get("restart_reentry_block_reason"),
            ),
        )
        task_id = rows[0]["id"] if rows else "?"
        logger.info("[shared] Task created: id=%s, priority=%s, depth=%d, parent=%s, mission=%s, agent=%s",
                     task_id, priority, depth, parent_task_id, mission_id, agent_type)
        return {"status": "ok", "task_id": task_id, "depth": depth, "mission_id": mission_id}
    except Exception as e:
        logger.error("[shared] create_task_in_db error: %s", e)
        return {"status": "error", "error": str(e)}


