#!/usr/bin/env bash
# Install per-service credential drop-ins from scripts/dropins/ into systemd,
# daemon-reload, and restart long-running services.
#
# Run as root:
#   /home/grass/leninbot/scripts/apply_credentials_dropin.sh
#
# The drop-in files are generated by scripts/migrate_secrets_to_credstore.py
# and reflect the SERVICE_CREDS least-privilege mapping defined there.
#
# Safe to re-run. Oneshot/timer-driven services (autonomous, experience,
# kg-backup) pick up the new drop-in on their next firing — they are not
# restarted here.

set -euo pipefail

PROJECT_ROOT=/home/grass/leninbot
DROPIN_SRC_DIR="${PROJECT_ROOT}/scripts/dropins"
MIGRATE_SCRIPT="${PROJECT_ROOT}/scripts/migrate_secrets_to_credstore.py"

echo "--- regenerating drop-ins ---"
"${PROJECT_ROOT}/venv/bin/python" "$MIGRATE_SCRIPT" | sed 's/^/    /'

if [[ ! -d "$DROPIN_SRC_DIR" ]]; then
  echo "ERROR: drop-in source dir not found at $DROPIN_SRC_DIR" >&2
  exit 1
fi

LONG_RUNNING=(
  leninbot-api
  leninbot-telegram
  leninbot-browser
)

echo "--- installing per-service drop-ins ---"
for src in "$DROPIN_SRC_DIR"/*.conf; do
  svc=$(basename "$src" .conf)
  dst_dir=/etc/systemd/system/${svc}.service.d
  mkdir -p "$dst_dir"
  cp "$src" "$dst_dir/credentials.conf"
  n_creds=$(grep -c '^LoadCredentialEncrypted=' "$src" || true)
  echo "  + $dst_dir/credentials.conf  (${n_creds} creds)"
done

echo "--- daemon-reload ---"
systemctl daemon-reload

echo "--- restarting long-running services ---"
systemctl restart "${LONG_RUNNING[@]}"

echo "--- status ---"
systemctl is-active "${LONG_RUNNING[@]}"

echo "--- recent warnings/errors (last 1 min) ---"
journalctl $(printf -- '-u %s ' "${LONG_RUNNING[@]}") \
  --since "1 minute ago" -p warning..err --no-pager | tail -20 || true

echo "done."
